version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./db/estrutura.sql:/docker-entrypoint-initdb.d/estrutura.sql

  app:
    image: python:3.9-slim
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./app:/app
    working_dir: /app
    command: >
      bash -c "pip3 install --no-cache-dir -r requirements.txt && python main.py"